spring:
  datasource:
    username: beer_inventory_service
    password: password
    url: jdbc:mysql://192.168.99.101:3306/beerinventoryservice?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC    hikari:
      data-source-properties:
        cachePrepStmts: true
        cacheResultSetMetadata: true
        cacheServerConfiguration: true
        elideSetAutoCommits: true
        maintainTimeStats: false
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        rewriteBatchedStatements: true
        useLocalSessionState: true
        useServerPrepStmts: true
      maximum-pool-size: 5  jpa:    database: mysql
    hibernate:      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect


# Enable logging for config troubleshooting
#logging:
#  level:
#    com:
#      zaxxer:
#        hikari:
#          HikariConfig: DEBUG
#    org:
#      hibernate:
#        SQL: DEBUG
#        type:
#          descriptor:
#            sql:
#              BasicBinder: TRACE